"""empty message

Revision ID: 139095258014
Revises: 4c43e4c57df2
Create Date: 2021-04-28 10:16:52.932943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139095258014'
down_revision = '4c43e4c57df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
