"""empty message

Revision ID: 293113a0121f
Revises: c665793318c4
Create Date: 2021-04-28 09:42:37.267007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293113a0121f'
down_revision = 'c665793318c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
