"""empty message

Revision ID: 849fba755335
Revises: f0c8c2a80dd2
Create Date: 2021-04-23 22:38:34.321626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849fba755335'
down_revision = 'f0c8c2a80dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_content')
    # ### end Alembic commands ###
