"""empty message

Revision ID: c3bf56f77198
Revises: 5fb8d886d49b
Create Date: 2021-04-22 23:48:51.913448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bf56f77198'
down_revision = '5fb8d886d49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_path')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
