"""empty message

Revision ID: f0c8c2a80dd2
Revises: 734b1aed13e5
Create Date: 2021-04-23 21:55:55.338710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c8c2a80dd2'
down_revision = '734b1aed13e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_title', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'category_title')
    # ### end Alembic commands ###
